monsieurbiz_contact_request_admin_contact_request:
    resource: |
        alias: monsieurbiz_contact_request.contact_request
        section: admin
        templates: "@SyliusAdmin/Crud"
        redirect: index
        except: ['update', 'create', 'show']
        grid: monsieurbiz_contact_request
        vars:
            index:
                icon: 'phone'
                header: 'monsieurbiz.contact_request.ui.contact_requests'
                breadcrumb: 'monsieurbiz.contact_request.ui.contact_requests'
    type: sylius.resource

monsieurbiz_contact_request_admin_contact_request_show:
    path: /contact-requests/{id}
    methods: [ GET ]
    defaults:
        _controller: monsieurbiz_contact_request.controller.contact_request::showAction
        _sylius:
            section: admin
            template: "@MonsieurBizSyliusContactRequestPlugin/Admin/ContactRequest/Crud/show.html.twig"
            permission: true
