services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Sylius\Bundle\ResourceBundle\Controller\ResourceController:
      autowire: false
    Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
      autowire: false
    Sylius\Component\Resource\Model\ResourceInterface:
      autowire: false